version: '3.9'

volumes:
  pgdata:


services:

  db:
    image: postgres
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: booksauction
